### ISSUE TITLE
Why not merge two awesome projects

### ISSUE THREAD

**Issue by cassiobotaro** [fkromer/awesome-fastapi#3]
Today we have this repository and [this](https://github.com/mjhea0/awesome-fastapi). Why not join forces? What do you think of this? @mjhea0 @fkromer

**Comment by fkromer** [comment]
@cassiobotaro @mjhea0 I'm fine with merging content into [this](https://github.com/mjhea0/awesome-fastapi) :wink: I'll archive my repo and reference the other repo. I won't merge content however. Everyone is welcomed to copy paste content.

**Comment by cassiobotaro** [comment]
I check each resource and submit some PRs. Thank you @fkromer . When you want, you can do the process of creating a reference for the other project and archive this one.
